version: 2.1

description: |
  Run screenshot tests via happo.io in your project. API tokens are read from
  $HAPPO_API_KEY and $HAPPO_API_SECRET, or directly from `apiKey` and `apiToken`
  if you have them listed in your `.happo.js` config.
  
display:
    source_url: https://github.com/happo/happo-circleci-orb
    home_url: https://happo.io/
commands:
  run_happo:
    description: |
      Run Happo in the current directory.
    steps:
      - run:
          name: Run Happo
          command: npx --package=happo.io happo-ci-circleci

  install_dependencies:
    description: |
      Install package dependencies via yarn or npm (auto-detects).
    steps:
      - run:
          name: Install dependencies
          command: |
            if [ -f 'yarn.lock' ]; then
              yarn install --pure-lockfile
            else
              npm install --no-save
            fi
jobs:
  run:
    description: |
      Check out code, install dependencies, then run Happo.
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - install_dependencies
      - run_happo

examples:
  run_happo_command:
    description: |
      Use the provided `happo/run_happo` command in a custom job.
    usage:
      version: 2.1
      orbs:
        happo: happo/happo@latest
      jobs:
        happo:
          docker:
            - image: <a node docker image>
          steps:
            - checkout
            - npm install
            - happo/run_happo

  use_happo_job:
    description: |
      Use the provided `happo/run` job directly.
    usage:
      version: 2.1
      orbs:
        happo: happo/happo@latest
      workflows:
        version: 2.1
        run_all:
          jobs:
            - happo/run
